name: Playwright Cucumber Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest   # ✅ No machine needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: npm test
